### ISSUE TITLE
Accept `authoritativeSource` as field name for authoritative sources

### ISSUE THREAD

**Issue by strogonoff** [geolexica/jekyll-geolexica#12]
Currently it’s just `authoritative_source`, but we use `authoritativeSource` in some authoring software.

**Comment by ronaldtse** [comment]
From https://github.com/glossarist/glossarist-ruby/issues/74#issuecomment-1656718301
> Why do we want to use "authoritativeSource" instead of the "sources -> type: authoritative" now?

**Comment by ronaldtse** [comment]
See this for the current setup:
https://github.com/glossarist/glossarist-ruby/blob/39eaea0d7755cea28ae07ff77740d8f2a0ea3c91/spec/fixtures/concept_collection/concept-3.1.1.2.yaml#L17-L22

**Comment by ronaldtse** [comment]
In the Concept YAML file, either we use all snake case, or we use all camel case. If we want to support both for particular keys, then we should support both for all keys.

**Comment by HassanAkbar** [comment]
This is where the [authoritativeSource](https://github.com/MetaverseStandards/metaversestandards-glossary/blob/main/msfglossary/localized-concept/06e4adb1-b7fb-42e7-8ba0-7122ed190d75.yaml#L12) is, but after looking a bit more I just realized that this is not the glossarist format I think it is `paneron`. Should we convert this to glossarist format or update glossarist?

@ronaldtse What do you suggest?

**Comment by ronaldtse** [comment]
@HassanAkbar Paneron and the Glossarist gem share 1 single YAML structure, which is the "Glossarist YAML structure".

**Comment by HassanAkbar** [comment]
@ronaldtse Got it, Then should we update the yaml file to use `authoritative_source` or should we update glossarist to handle camel casing?

**Comment by strogonoff** [comment]
> This is where the [authoritativeSource](https://github.com/MetaverseStandards/metaversestandards-glossary/blob/main/msfglossary/localized-concept/06e4adb1-b7fb-42e7-8ba0-7122ed190d75.yaml#L12) is, but after looking a bit more I just realized that this is not the glossarist format I think it is `paneron`. Should we convert this to glossarist format or update glossarist?
> 
> @ronaldtse What do you suggest?

@HassanAkbar 

There is a bit of misunderstanding.
- There is no “paneron” structure per se that needs to be supported, there is Glossarist register structure
- Glossarist register structure used to be simple YAML files in a folder, but now it’s more complicated (Glossarist model v2)
- (Paneron app is using Glossarist model v2)
- [Test fixtures](https://github.com/glossarist/glossarist-ruby/tree/main/spec/fixtures/concept_collection) for glossarist-ruby are outdated, they use the old model
- However, I can see that https://glossary.metaverse-standards.org for example is built successfully, and I think the build uses Glossarist model v2, which makes me think Ruby supports it even if tests use old fixtures. I don’t know why or how

To repeat, there were *many* changes made in Glossarist 2 model (like splitting register items into `localized-concept` and `concept` directories), so the test spec is *very* outdated, but despite that sites seem to build anyway (?), except for `authoritativeSource` field. So I recommend updating to recognize both `authoritativeSource` and `authoritative_source` fields first to un-break MSF glossary for example, and afterwards taking care of updating tests fully to new data structure…

**Comment by HassanAkbar** [comment]
> - There is no “paneron” structure per se that needs to be supported, there is Glossarist register structure
> - Glossarist register structure used to be simple YAML files in a folder, but now it’s more complicated (Glossarist model v2)

Got it, Thanks for clarification.

> - [Test fixtures](https://github.com/glossarist/glossarist-ruby/tree/main/spec/fixtures/concept_collection) for glossarist-ruby are outdated, they use the old model

Actully, the `glossarist-ruby` gem is currently not updated to support the Glossarist model v2, I'll create an issue for that there.

> - However, I can see that https://glossary.metaverse-standards.org/ for example is built successfully, and I think the build uses Glossarist model v2, which makes me think Ruby supports it even if tests use old fixtures. I don’t know why or how

After looking at the code for a while I realized that this is happening because currently glossarist is not being used to read the concept files they are being processed inside the [jekyll-geolexica](https://github.com/geolexica/jekyll-geolexica) gem. 

@strogonoff @ronaldtse I think we should update `jekyll-geolexica` to use glossarist and update glossarist to support model v2.

For a quick fix I can open a PR for supporting camel casing for `authoritativeSource` here. What do you suggest?

**Comment by strogonoff** [comment]
> @strogonoff @ronaldtse I think we should update `jekyll-geolexica` to use glossarist and update glossarist to support model v2.
> 
> For a quick fix I can open a PR for supporting camel casing for `authoritativeSource` here. What do you suggest?

I think this makes sense:

1. start supporting `authoritativeSource`,
2. support current Glossarist 2 model in `glossarist-ruby`,
3. switch `jekyll-geolexica` to use `glossarist-ruby` with thorough testing on existing website repositories to ensure no undesired changes happen when they are later deployed.

In that order…

**Comment by HassanAkbar** [comment]
`jekyll-geolexica` and `glossarist-ruby` serves different purposes `glossarist` is used to convert `yaml` files into ruby objects and currently `jekyll-geolexica` is doing that manually so, I think point 3 should be to update `jekyll-geolexica` to use `glossarist-ruby` instead of reading `yml` files directly.

@ronaldtse @strogonoff what do you suggest?

**Comment by strogonoff** [comment]
When I wrote

> switch `jekyll-geolexica` to use `glossarist-ruby`

I did not mean “replace `jekyll-geolexica` with `glossarist-ruby`”, I meant “switch internal implementation of `jekyll-geolexica` to use `glossarist-ruby` [instead of interpreting Glossarist data directly]”.

@HassanAkbar, does it make sense?

This part can be done after the other steps. And before this part is released, sites will still need to be tested fully to avoid unintended changes and regressions in final HTML, which is possible due to switching Glossarist data interpretation logic to another implementation.

**Comment by strogonoff** [comment]
> > @strogonoff @ronaldtse I think we should update `jekyll-geolexica` to use glossarist and update glossarist to support model v2.
> > For a quick fix I can open a PR for supporting camel casing for `authoritativeSource` here. What do you suggest?
> 
> I think this makes sense:
> 
> 1. start supporting `authoritativeSource`,
> 2. support current Glossarist 2 model in `glossarist-ruby`,
> 3. switch `jekyll-geolexica` to use `glossarist-ruby` with thorough testing on existing website repositories to ensure no undesired changes happen when they are later deployed.
> 
> In that order…

This issue is closed because step (1) was done. @HassanAkbar do you want me to file separate issues for (2) and (3) or you’ll handle it?

**Comment by HassanAkbar** [comment]
@strogonoff Created the issues for point (2) and (3)
- https://github.com/glossarist/glossarist-ruby/issues/76
- https://github.com/geolexica/jekyll-geolexica/issues/14
