### ISSUE TITLE
Recognize modification notes from authoritative source relationship field

### ISSUE THREAD

**Issue by strogonoff** [geolexica/jekyll-geolexica#16]
Example rendered item missing source relationship modification note: https://glossary.metaverse-standards.org/concepts/110/

Same item’s source containing “modified” relationship and modification note: https://github.com/MetaverseStandards/metaversestandards-glossary/blob/14600de6147180834ef0d5fc6c7fdc5ca4969d46/msfglossary/localized-concept/f2c8bcd6-f1ab-433f-97a6-187ca3a0fb5a.yaml#L20-L22

We would want to display relationship & optional modification note in a way that is similar to how it looks here: https://isotc211.geolexica.org/concepts/10/ (see source field).

**Comment by strogonoff** [comment]
@HassanAkbar have you confirmed that the modification note is being displayed? It’s not being displayed for me.

**Comment by HassanAkbar** [comment]
@strogonoff The site has not been redeployed yet, will let you know once that is done.

**Comment by HassanAkbar** [comment]
@strogonoff Need to update `geolexica-site` version to `1.7.8` in here https://github.com/MetaverseStandards/glossary.metaverse-standards.org/blob/main/Gemfile, 
But I don't have the write access there, can you help me with that?

**Comment by strogonoff** [comment]
There’s some build error coming from `mercenary` apparently? (https://github.com/MetaverseStandards/glossary.metaverse-standards.org/actions/runs/6979158382)

**Comment by HassanAkbar** [comment]
@strogonoff the build is failing due to incompatibility of `jekyll-4.2.2` with `logger-1.6.0`. The [Jekyll's PR](https://github.com/jekyll/jekyll/pull/9392) for the fix is merged and will be available in the next release of `Jekyll`, but for now we will have to lock the `logger` version to `1.5.3`. 

I've verified that it works on logger version `1.5.3`. So, I'll update all the related gems and let you know.

cc: @ronaldtse

**Comment by HassanAkbar** [comment]
@strogonoff The issue should be fixed now, can you try again with `geolexica-site` version to `1.7.9`.

**Comment by strogonoff** [comment]
It works now! Thanks @HassanAkbar.
